### ISSUE TITLE
Admin should receive notification when there are permission requests

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#615] opened 2015-08-13 18:17 UTC
The admins should receive a notification if there is a permission request. Right now they have to go to the admin dashboard and check to see if there are any. I could see many requests going unanswered.

**Comment by gliese1337** [comment] 2015-12-16 01:38
Duplicate of #560.

**Closed by gliese1337** 2015-12-16 01:38 UTC
Labels: Enhancement, Functionality, Priority 2
