### ISSUE TITLE
Content marked "Private" shows up in courses that it has been added into

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#533] opened 2015-06-11 21:19 UTC
Right now a user can have content set as "Private" but the content still shows up in a course content.

When a student in the course clicks on that content, they get an "Oh Snap! You cannot do that." Error.

![privatecontentstillshowsupinacourse](https://cloud.githubusercontent.com/assets/5481718/8118600/38d67cbc-104d-11e5-8883-59c604c364c5.gif)

What should happen is that if a teacher sets content as private then the video does not show up in the course at all.

**Comment by gliese1337** [comment] 2015-06-12 20:16
This is a duplicate of #151

**Closed by gliese1337** 2015-06-12 20:16 UTC
Labels: duplicate
