### ISSUE TITLE
Make thumbnail function not working

### ISSUE THREAD

**Issue by natatat9** [BYU-ARCLITE/Ayamel-Examples#755] opened 2016-03-04 19:17 UTC
After having clicked "Make thumbnail" (found under the edit menu and selecting "set thumbnail")  Ayamel sends back a "Oh Snap, no files found" message

![image](https://cloud.githubusercontent.com/assets/16259543/13537532/a2506bb2-e202-11e5-9a8a-5dce6c8aa983.png)

Link to replicate:
https://ayamel.byu.edu/content/3283

I found this problem on myPC, both in Chrome and in Firefox

**Comment by gliese1337** [comment] 2016-03-05 03:56
Duplicate of #609

**Closed by gliese1337** 2016-03-05 03:56 UTC
