### ISSUE TITLE
Main: Newly created caption tracks are not saving to the server

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#689] opened 2015-10-26 22:48 UTC
I am unable to save newly created caption tracks (ones that I am creating within CaptionAider/ ones I did not upload). I click save and nothing ever happens. I don't get a notification that things have saved. I can, however, save to disk and then upload the track, but that is messy.  Moreover I can make changes to an existing caption track and then save it. I then get a notification that these changes have saved. BUT when I go to watch the video, the changes do not show up until after I've cleared my cache which is always frustrating 
URL to video I was working with: https://ayamel.byu.edu/content/2442

**Comment by JKJensen** [comment] 2015-10-27 22:12
This "not saving" problem is resulting in strange bugs.

This video has subtitles that the user uploaded, but he cannot view or turn them on in his own configuration menu.
https://ayamel.byu.edu/content/2813

Access his bug by going to: https://ayamel.byu.edu/admin/users
And proxying as the user: "ryler1"

**Comment by dro248** [comment] 2015-11-23 18:18
Is this the same bug as #677 ?

**Comment by gliese1337** [comment] 2015-11-26 00:39
It could very well be a duplicate of #677. @JKJensen & @schyatt : have you replicated this problem on the Beta site?

**Comment by gliese1337** [comment] 2015-12-09 18:08
Closing as duplicate due to non-replication.

**Closed by gliese1337** 2015-12-09 18:08 UTC
Labels: Bug, CaptionAider, Mac, PC, Priority 1
