### ISSUE TITLE
Clicking on transcription to go to a specific place in the video does not work after you click on a content annotation.

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#499] opened 2015-03-20 21:55 UTC
Clicking on transcription to go to a specific place in the video does not work after you click on a content annotation.
I clicked on the annotated word, "la pluie". I watched the annotation video, but not all of the way. 
After that, I tried to jump to a specific place in the video by clicking on the transcript, and it did not let me. 
After reloading the video, the transcript-jump worked. 
It only happened after clicking on the content annotation, the other types of annotations did not break it. 

video url: http://ayamel.byu.edu/course/336/content/1932

**Comment by verdude** [comment] 2015-05-07 22:49
Note: The transcript is not broken after you load a content annotation. Clicking on a cue then changes the current time of the content annotation instead of the main player.

**Comment by gliese1337** [comment] 2015-05-23 02:53
This is a result of the ContentRenderer system using a single global variable for the page to hold a reference to the main player. The same ContentRenderer system is re-used to load content annotations, and it overwrites the global variable.

There's no way to fix this without some major architectural changes. We either need to write a separate system for rendering content annotations apart from main content, or rewrite the whole main content rendering system to eliminate globals.

This isn't a regression; the erroneous code has been in there pretty much forever, just remaining unnoticed, so I don't consider fixing this to be terribly high priority for the next release. The best solution would be to just finish the process of moving the side panels into the Ayamel Player; which will make the issue obsolete.

**Comment by gliese1337** [comment] 2015-07-14 22:44
Hard to check for sure because the transcript clicking is now broken, but this should be fixed.

**Closed by gliese1337** 2015-07-14 22:44 UTC
Labels: Annotations, Ayamel Player, Bug, Chrome, PC
