### ISSUE TITLE
Admin Cannot Remove Permissions from a User

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#549] opened 2015-06-16 22:29 UTC
An Admin is unable to remove permissions from a user. With this user, I gave them the right to create courses and then could not take that right away. (The 2nd part of the .gif was supposed to show that they had the ability under my courses, but it wasn't in the screenshot... 
![permissions](https://cloud.githubusercontent.com/assets/10120523/8196070/d8c14dc4-1444-11e5-8494-c6dc99fe97d7.gif)

**Comment by gliese1337** [comment] 2015-06-17 11:28
Most likely a duplicate of #542

**Closed by gliese1337** 2015-06-17 11:28 UTC
Labels: Bug, duplicate
