### ISSUE TITLE
Add fields to batch upload

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#633] opened 2015-08-19 16:34 UTC
We would like to add fields to the batch upload to set visibility, shareability, and possibly one for an existing Ayamel Resource ID (if you want to batch edit existing files). This way users would not have to go set the shareability and visability for each individual video under configuration.

**Comment by gliese1337** [comment] 2015-08-25 23:11
Duplicate of #599

**Closed by gliese1337** 2015-08-25 23:11 UTC
Labels: Enhancement, Functionality
