### ISSUE TITLE
Annotations Displayed when Non Enabled

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#723] opened 2016-01-12 22:51 UTC
These were being displayed so I enabled them, then disabled them. They still show up:

![image](https://cloud.githubusercontent.com/assets/7268293/12279396/112a399c-b944-11e5-888d-3101c947e0c3.png)

![image](https://cloud.githubusercontent.com/assets/7268293/12279418/31dca3fa-b944-11e5-92a3-f9416f59455a.png)

**Comment by gliese1337** [comment] 2016-01-23 04:01
URL?

**Comment by gliese1337** [comment] 2016-01-23 04:03
Duplicate of #671

**Closed by gliese1337** 2016-01-23 04:03 UTC
Labels: Bug, Priority 1
