### ISSUE TITLE
Main: Course Owner not getting notifications when people join their course via url or lti

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#690] opened 2015-10-26 22:59 UTC
The Course owner is not getting notifications when people join their course via url or lti. I don't know if this is how it is supposed to be, but I thought I'd let you know.
course url:  https://ayamel.byu.edu/course/392

**Comment by gliese1337** [comment] 2015-12-10 08:02
Duplicate of #560

**Closed by gliese1337** 2015-12-10 08:02 UTC
Labels: duplicate, Functionality, Priority 3
