### ISSUE TITLE
UI- Content Creators can adjust ordering of subtitle tracks/annotations

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#742] opened 2016-02-09 20:13 UTC
Right now, the very first subtitle track a user uploads is the first, and will always be the first until they delete it. If they want the third subtitle track to be first, they have to delete the first two and reupload them.

There should be a way to reorder these tracks.
The ideal method would be similar to iTunes, in which users can click and drag the track and move it to a desired location:
![adjusttrackordering](https://cloud.githubusercontent.com/assets/5481718/12929215/cc23530a-cf2e-11e5-9b5e-95b2cf1229b3.gif)

This reordering ability should take place in both the Text-> Captions/Subtitles AND the Text-> Annotations menus.

Ideally, the reordering should take place like iTunes in which users can simply click and drag.

But if it's easier to program, we could add another column into the caption tracks table where users can move the tracks around.
![adjusttrackordering](https://cloud.githubusercontent.com/assets/5481718/12929047/0b01166c-cf2e-11e5-8717-7458b8ed8816.png)

**Comment by gliese1337** [comment] 2016-02-10 03:26
Duplicate of #569

**Closed by gliese1337** 2016-02-10 03:26 UTC
Labels: Priority 3, UI/Look and feel
