### ISSUE TITLE
Captions won't save, kind of

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#471] opened 2015-02-06 16:21 UTC
The last bug I submitted was not 100% correct. The captions saved, but only after I logged out of Ayamel and then logged back on. It was the same for Firefox and Chrome.

**Comment by gliese1337** [comment] 2015-02-06 19:26
Duplicate of #470

**Closed by gliese1337** 2015-02-06 19:26 UTC
Labels: Bug, CaptionAider, Chrome, duplicate, Firefox
