### ISSUE TITLE
Caption Changes aren't saving

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#470] opened 2015-02-06 15:51 UTC
I changed the length and placement on some captions for the video Clement 1 on Ayamel. I saved it on the server and on my disk, and both said that it saved correctly. I then exited out of the captionaider, and when I played the video, none of the caption edits I made had saved. I tried this twice.

**Comment by gliese1337** [comment] 2015-02-06 19:27
Looks like we need to investigate what Chrome did to their caching rules and how to get around them again....

**Comment by shyatt** [comment] 2015-02-18 02:22
We have had a client that is using Ayamel that has run into this problem. I had him refresh his page, log out and then back in, but none of his changes had saved. I then did a test on the same movie and ran into the same problems. I have emailed you a screen cast. This was done on a PC.

**Comment by gliese1337** [comment] 2015-02-19 00:00
Duplicate of #149 & #35 . Verified to be a caching issue. Clear the cache, and everything works fine. I'll leave this open in case there's anything we can do to improve the cache-invalidation code.

**Comment by gliese1337** [comment] 2015-03-06 21:16
After more research, it looks like there is currently nothing we can do that is guaranteed to work across all browsers all the time. Everybody ignores caching rules. Bleh. Closing since it looks like there's nothing we can do about this, and a workaround is known.

**Closed by gliese1337** 2015-03-06 21:16 UTC
Labels: Bug, CaptionAider, Chrome
