### ISSUE TITLE
Using LTI to Connect to Ayamel from Canvas

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#513] opened 2015-05-29 16:40 UTC
Chrome throws errors when connecting from Canvas via https to Ayamel using LTI due to its making non-https calls while using https.

![https](https://cloud.githubusercontent.com/assets/7268293/7887498/c3ed251c-05ee-11e5-964b-0506c47b70a0.JPG)

**Comment by DigitalProf** [comment] 2015-05-29 17:26
The same problem occurs when accessing course content via https, due to the same, previously reported problem.

**Comment by DigitalProf** [comment] 2015-06-12 22:49
The above reported but Ayamel does not log me in:

![image](https://cloud.githubusercontent.com/assets/7268293/8141367/01356ce2-1123-11e5-8402-155695f6a43d.png)

**Comment by gliese1337** [comment] 2015-06-26 21:57
With HTTPS issues resolved, this becomes a duplicate of #414

**Closed by gliese1337** 2015-06-26 21:57 UTC
Labels: Bug, duplicate

**Comment by DigitalProf** [comment] 2015-06-26 22:25
I should add that I was just testing using the Production Site and not the Beta site...

From: Michael Bush
Sent: Friday, June 26, 2015 4:24 PM
To: Logan Kearsley (chronosurfer@gmail.com); Shari Hyatt (s.messick626@gmail.com)
Cc: 'BYU-ARCLITE/Ayamel-Examples'; BYU-ARCLITE/Ayamel-Examples
Subject: RE: [Ayamel-Examples] Using LTI to Connect to Ayamel from Canvas (#513)

For the testing of this portion of the system please look at these issues in light of my earlier message today in which I provided instructions as to how to test this with Canvas.

Many thanks!

**Comment by DigitalProf** [comment] 2015-06-26 22:25
For the testing of this portion of the system please look at these issues in light of my earlier message today in which I provided instructions as to how to test this with Canvas.

Many thanks!
