### ISSUE TITLE
Trying to add captions to a video with the autocue setting using Google Chrome 

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#465] opened 2015-01-30 15:32 UTC
When trying to upload text on Captionaider, it does not work on Google Chrome (but it does on Firefox). I right click in the French subtitle track, highlight track, highlight auto settings, and then my options to add to line buffer and start auto cue do not show up.
Here is a screen shot of Google Chrome:
![image](https://cloud.githubusercontent.com/assets/10120523/5978046/055f1a34-a85a-11e4-9440-eb18052ec691.png)

Here is a screen shot of what it should look like from Firefox:
![image](https://cloud.githubusercontent.com/assets/10120523/5978103/8806be7e-a85a-11e4-82f0-55fe3db6a532.png)

**Comment by gliese1337** [comment] 2015-01-30 22:00
This appears to be a duplicate of a previous bug which apparently did not get properly Github-recorded, because I can't find it. As far as we can tell, it's an error in Chrome's CSS rendering which causes third-level menu items not to show up if they are positioned in certain places. The menu items are properly created, and should still work if you can manage to click on them despite them being invisible, Chrome just fails to properly draw them. We never found a way to work around that before, and after a couple more automatic updates to Chrome the problem went away.

Rather than spin wheels trying to work around it again, I'm just going to close this issue and hope it resolves itself after another couple of Chrome updates. If it becomes critical at some point, we can re-open it.

**Closed by gliese1337** 2015-01-30 22:00 UTC
Labels: Bug, CaptionAider, Chrome
