### ISSUE TITLE
Batch Upload isn't user friendly

### ISSUE THREAD

**Issue by dro248** [BYU-ARCLITE/Ayamel-Examples#708] opened 2015-11-19 20:46 UTC
After tinkering with the batch upload utility, I figured out how it works. It **does** work.

However, from a UX perspective, the batch upload utility lacks functionality on 3 different levels:
* Fails to notify user if batch upload script has been rejected
* Fails to notify user if a batch upload is in progress
* Instructions for creating a batch upload script are not completely definitive, forcing a certain amount of guesswork into the script creation process

To address this issue, I recommend a few different options:
1. Notify user if script is rejected
2. Create a progress bar gui that allows the user to see progress of upload
3. Write a more definitive guide to creating a batch upload script
4. Add a tool onto the batch upload utility which allows a user to create a batch directly from the browser.

**Comment by gliese1337** [comment] 2015-11-23 19:10
Duplicate of #168

**Closed by gliese1337** 2015-11-23 19:10 UTC
Labels: duplicate, Enhancement, Functionality, UI/Look and feel
