### ISSUE TITLE
North Levanine Arabic and Egyptian in language list

### ISSUE THREAD

**Issue by natatat9** [BYU-ARCLITE/Ayamel-Examples#744] opened 2016-02-10 21:06 UTC
We would like to get North Levantine Arabic and Egyptian added to the language list in the "edit Metadata" tab (found under the edit tab)
Link to replicate:  https://ayamel.byu.edu/content/1386  (this video is currently listed as English, but should be North Levantine Arabic)

Let me know if you need more a description 
![image](https://cloud.githubusercontent.com/assets/16259543/12961786/71693872-cfff-11e5-88cc-ddce0d9227b3.png)

**Comment by gliese1337** [comment] 2016-02-10 22:25
Duplicate of #738

**Closed by gliese1337** 2016-02-10 22:25 UTC
