### ISSUE TITLE
Caption Tracks Are Displayed Twice in CaptionAider

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#647] opened 2015-08-31 17:58 UTC
CaptionAider is having some strange issues at this moment. The first is that once you open up a caption track to edit, you can no longer scroll down and see the controls on the player. The next is that the caption track you are editing shows up twice on the video player. The third is that the caption cue seem to be double spaced in format (there is an extra space when you put a line break in a cue).
URL:  https://ayamel.byu.edu/content/1989
![captionaider](https://cloud.githubusercontent.com/assets/10120523/9586020/8e9c1f02-4fd7-11e5-94a2-4ba916511c11.gif)

**Comment by johnlarson** [comment] 2015-08-31 20:08
What computer were you on? I can't reproduce it on mine.

Did someone fix this?

**Comment by schyatt** [comment] 2015-08-31 21:39
I am on a PC(Dell)  using Chrome.

**Comment by DigitalProf** [comment] 2015-09-02 20:46
I just saw the double-track issue as well. I received an error when trying to save:

![image](https://cloud.githubusercontent.com/assets/7268293/9643807/4430ec44-5181-11e5-87de-212a8cc659eb.png)

Here are the messages from the console:
![image](https://cloud.githubusercontent.com/assets/7268293/9643753/0ed7e8d6-5181-11e5-8bf7-587d5940ee2e.png)

**Comment by gliese1337** [comment] 2015-09-03 00:28
Could you please pick 1 problem to track here and create separate issues for the other two?

**Comment by DigitalProf** [comment] 2015-09-03 14:33
I received similar results editing captions on a YouTube video:
https://ayamel.byu.edu/captionaider/2107/0
Choosing from the two captions tracks (English and Test), loaded English to the timeline and selected it for display on the video. When  I selected Test for display, the caption was displayed twice. When I deselected the Test track for display, only one disappeared, and the other remained. 

Just after selecting the Test caption track for display:
![image](https://cloud.githubusercontent.com/assets/7268293/9661072/3c9e3a32-5216-11e5-9730-58ee845f789c.png)

Just after deselecting the Test caption track for display:

![image](https://cloud.githubusercontent.com/assets/7268293/9661098/636c621a-5216-11e5-8ef3-a15c7ca550d3.png)

**Comment by DigitalProf** [comment] 2015-09-03 14:48
Logan and John,

I did what Logan requested, and this issue is now quite reproducible, at least with this video<https://ayamel.byu.edu/captionaider/2107/0>.

Because this seems to me to be player-related, I am thinking that if John can get to it first today, then I would like for him to hold a bit on HLS to have a look.

Many thanks!

Cheers,

Prof Bush

**Comment by DigitalProf** [comment] 2015-09-03 15:40
Logan and John,

After a bit more testing, I am even more convinced that the problems we are seeing with CaptionAider are related to changes in the player. I have documented my findings Issue #653.

We need for one of you to check this out as soon as possible.

Many thanks!

Cheers,

Prof Bush

P.S.

By the way, I note that the Jump Back and Jump Forward buttons are now working on Brightcove videos and express great appreciation:

[cid:image001.png@01D0E62C.9090C2A0]

I am sending a note to my students right now!

**Comment by schyatt** [comment] 2015-09-03 21:46
These are issues on both the main and beta sites.

**Comment by gliese1337** [comment] 2015-09-10 02:32
Just did some more playing around with this. Apparently, it was unrelated to the other two editor bugs ( #649 & #653 ). Confirmed that it only happens in CaptionAider, so the error has to be a result of interactions between the editing system and the caption renderer. It looks like all captions are rendered twice, but the second copy is somehow leaked, so it doesn't get cleaned up by the renderer when the cue ends, and it doesn't affect the layout of later cues. Other actions that should trigger a refresh/rebuild, like resizing the screen, also do not remove the left-overs, so they're really truly disconnected from the system. That suggests that it's not as simple as two copies of each track accidentally getting registered with the renderer. Edits to the extra copies *do*, however, end up reflected in the timeline, so they are being connected to a CaptionEditor object.

So, we need to find what's causing a duplication of DOM elements for rendered cues, including the event listeners that attach them to the cue text editing system, and accurately positions the duplicates around other captions on the screen, but does not register the duplicates with the renderer for later cleanup.

**Comment by gliese1337** [comment] 2015-09-10 02:36
More experimenting: if tracks are activated for viewing without being loaded into the timeline editor, the problem does not appear. Once they are loaded in the editor, though, the duplication continues to occur even after the track is later removed from the editor.
Additionally, the leaked, leftover cues only occur when more than one track has been activated. And they do not always occur even when more than one track has been activated. The bug seems to be highly path dependent.

**Comment by gliese1337** [comment] 2015-09-10 03:44
Turns out it did all come down to adding the same track to the renderer multiple times on accident. For whatever reason, just duplicating those tracks had all kinds of path-dependent effects.

The Caption Renderer had actually previously been updated to make adding tracks idempotent, so that it was impossible to have multiple copies of the same track no matter what. This is why I could not duplicate the problem on my local machine, and probably why @johnlarson couldn't duplicate it either. But, the fixed code was never pushed to sartre! So, I pushed the fixed code to sartre. :) And now everything seems to work just like it's supposed to.

**Comment by schyatt** [comment] 2015-09-11 21:51
This is happening again on the main site, but only for the second subtitle track.
Here is the url for the video:  https://ayamel.byu.edu/content/2082
![english](https://cloud.githubusercontent.com/assets/10120523/9827166/e7eaec14-589c-11e5-9fb8-5c7ba5b0b354.PNG)

**Comment by gliese1337** [comment] 2015-09-11 23:01
I'm not seeing it. Did you try clearing your cache after the fix?

**Closed** 2015-09-15 17:05 UTC
Labels: Bug, CaptionAider, Priority 1
